# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: cgregory <cgregory@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/10/08 19:34:04 by cgregory          #+#    #+#              #
#    Updated: 2022/11/02 20:31:47 by cgregory         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME		=	libft.a
SRCS		=	ft_bzero.c		ft_isalnum.c	ft_isalpha.c\
				ft_isascii.c	ft_isdigit.c	ft_isprint.c\
				ft_memset.c		ft_strlen.c		ft_tolower.c\
				ft_toupper.c	ft_strchr.c		ft_strrchr.c\
				ft_strncmp.c	ft_memcpy.c		ft_memmove.c\
				ft_memchr.c		ft_memcmp.c\
				ft_strlcpy.c	ft_strlcat.c	ft_strnstr.c\
				ft_atoi.c		ft_calloc.c		ft_strdup.c\
				ft_putchar_fd.c	ft_putstr_fd.c	ft_putnbr_fd.c\
				ft_putendl_fd.c	ft_substr.c		ft_strjoin.c\
				ft_strtrim.c	ft_itoa.c		ft_split.c\
				ft_strmapi.c	ft_striteri.c
SRCSB		=	ft_lstnew.c			ft_lstadd_front.c\
				ft_lstsize.c		ft_lstlast.c\
				ft_lstadd_back.c	ft_lstdelone.c\
				ft_lstclear.c		ft_lstiter.c\
				ft_lstmap.c
HEADER		=	libft.h
HDRDIR		=	./
OBJ			=	$(SRCS:%.c=%.o)
OBJB		=	$(SRCSB:%.c=%.o)
CC			=	gcc
CFLAGS		=	-Wall -Wextra -Werror
.PHONY		:	all	bonus clean	fclean re
all			:	$(NAME)
bonus		:	$(OBJB) $(HDRDIR)$(HEADER)
				@ar rcs $(NAME) $?
$(NAME)		:	$(OBJ) $(HDRDIR)$(HEADER)
				@ar rcs $(NAME) $?
				@echo "$(BLUE)libft: library created$(DEFAULT)"
%.o			:	%.c $(HDRDIR)$(HEADER)
				@$(CC) $(CFLAGS) -I$(HDRDIR) -c $< -o $@
clean		:	
				@rm -rf $(OBJ) $(OBJB)
				@echo "$(YELLOW)libft: obj files deleted$(DEFAULT)"
fclean		:	
				@rm -f $(NAME)
				@echo "$(RED)libft: all files deleted$(DEFAULT)"
re			:	fclean all

RED = \033[1;31m
GREEN = \033[1;32m
BLUE = \033[1;34m
YELLOW = \033[1;33m
DEFAULT = \033[0m
